CREATE TABLE membro(
	ID SERIAL PRIMARY KEY,
	NOME CHAR(255) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CERTIDAO_NASCIMENTO CHAR(32) UNIQUE NOT NULL,
	RG CHAR(9) UNIQUE NOT NULL,
	ORG_EXPEDIDOR CHAR(5) UNIQUE NOT NULL,
	CPF CHAR(11) UNIQUE,
	TELEFONE CHAR(9),
	EMAIL TEXT
	);

CREATE TABLE REPONSAVEL(
	ID SERIAL PRIMARY KEY,
	NOME CHAR(255) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CERTIDAO_NASCIMENTO CHAR(32) UNIQUE NOT NULL,
	RG CHAR(9) UNIQUE NOT NULL,
	ORG_EXPEDIDOR CHAR(5) NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL,
	TELEFONE CHAR(9) NOT NULL,
	EMAIL TEXT NOT NULL
	);

CREATE TABLE MEMBRO_RESPONSAVEL(
	membro_id SERIAL NOT NULL,
    responsavel_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	FOREIGN KEY (responsavel_id) REFERENCES REPONSAVEL(id)
	);
	
CREATE TABLE SAUDE(
	ID SERIAL PRIMARY KEY,
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	SUS CHAR(15) UNIQUE NOT NULL,
	TIPO_SANGUINEO CHAR(5) NOT NULL,
	PESO FLOAT NOT NULL,
	ALTURA FLOAT NOT NULL,
	ALERGIA BOOLEAN NOT NULL,
	CIRURGIA BOOLEAN NOT NULL
	);
	
CREATE TABLE PLANO_SAUDE(
	saude_id SERIAL NOT NULL,
	FOREIGN KEY (saude_id) REFERENCES saude(id),
	CONVENIO TEXT NOT NULL,
	CATEGORIA TEXT NOT NULL,
	CARTEIRA VARCHAR(20) UNIQUE NOT NULL
	);
	
CREATE TABLE ALERGIA(
	saude_id SERIAL NOT NULL,
	FOREIGN KEY (saude_id) REFERENCES saude(id),
	TIPO VARCHAR(50) NOT NULL,
	DESCRICAO TEXT NOT NULL,
	RECOMENDACAO TEXT
	);
	
CREATE TABLE CIRURGIA(
	saude_id SERIAL NOT NULL,
	FOREIGN KEY (saude_id) REFERENCES saude(id),
	TIPO VARCHAR(50) NOT NULL,
	DESCRICAO TEXT NOT NULL,
	DATA DATE NOT NULL
	);

CREATE TABLE endereco(
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	CEP CHAR(8) NOT NULL,
	rua VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	PAIS VARCHAR(50) NOT NULL,
	NUMERO integer NOT NULL,
	COMPLEMENTO VARCHAR(20)
	);
	
CREATE TABLE UNIDADE(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) UNIQUE NOT NULL,
	CLASSE VARCHAR(50) NOT NULL,
	RANGE_NASCIMENTO daterange NOT NULL
	);

CREATE TABLE MEMBRO_UNIDADE(
	membro_id SERIAL NOT NULL,
	unidade_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	FOREIGN KEY (unidade_id) REFERENCES unidade(id),
	CARGO VARCHAR(50) NOT NULL
	);
	
CREATE TYPE status_solicitacao AS ENUM ('pendente', 'enviado', 'devolvido');

CREATE TABLE SOLICITACAO(
	ID SERIAL PRIMARY KEY,
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	REUNIAO DATE NOT NULL,
	STATUS status_solicitacao NOT NULL
	);

CREATE TYPE status_patrimonio AS ENUM ('disponivel', 'quebrado', 'manutencao');

CREATE TABLE PASTRIMONIO(
	ID SERIAL PRIMARY KEY,
	ITEM TEXT NOT NULL,
	QUANTIDADE integer NOT NULL,
	STATUS status_patrimonio NOT NULL
	);

CREATE TABLE SOLICITACAO_PATRIMONIO(
	patrimonio_id SERIAL NOT NULL,
	solcitacao_id SERIAL NOT NULL,
	FOREIGN KEY (patrimonio_id) REFERENCES PASTRIMONIO(id),
	FOREIGN KEY (solcitacao_id) REFERENCES SOLICITACAO(id)
	);
	
CREATE TABLE EVENTO(
	ID SERIAL PRIMARY KEY,
	NOME TEXT NOT NULL,
	DATA daterange NOT NULL,
	VALOR FLOAT NOT NULL
	);
	
CREATE TABLE EVENTO_MEMBRO(
	evento_id SERIAL NOT NULL,
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (evento_id) REFERENCES evento(id),
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	INSCRITO BOOLEAN NOT NULL,
	PAGO BOOLEAN NOT NULL
	);
	
CREATE TABLE STORE(
	ID SERIAL PRIMARY KEY,
	ITEM TEXT NOT NULL,
	VALOR FLOAT NOT NULL
	);

CREATE TABLE STORE_MEMBRO(
	store_id SERIAL NOT NULL,
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (store_id) REFERENCES STORE(id),
	FOREIGN KEY (membro_id) REFERENCES membro(id)
	);

CREATE TYPE TYPE_MENSALIDADE AS ENUM ('mensal', 'anual');

CREATE TABLE MENSALIDADE_MEMBRO(
	ID SERIAL PRIMARY KEY,
	membro_id SERIAL NOT NULL,
	FOREIGN KEY (membro_id) REFERENCES membro(id),
	DATA_PAGAMENTO DATE NOT NULL,
	TYPE TYPE_MENSALIDADE NOT NULL
	);
	
	
CREATE TABLE avisos(
	ID SERIAL PRIMARY KEY,
	DATA DATE NOT NULL,
	TEXTO TEXT NOT NULL
	);
	
CREATE TABLE atividades(
	ID SERIAL PRIMARY KEY,
	DATA DATE NOT NULL,
	TEXTO TEXT NOT NULL
	);
	
CREATE TABLE atividade_unidade(
	atividade_id SERIAL NOT NULL,
	FOREIGN KEY (atividade_id) REFERENCES atividades(id),
	unidade_id SERIAL NOT NULL,
	FOREIGN KEY (unidade_id) REFERENCES unidade(id),
	status BOOLEAN NOT NULL
	);
	
CREATE TABLE avisos_unidade(
	aviso_id SERIAL NOT NULL,
	FOREIGN KEY (aviso_id) REFERENCES avisos(id),
	unidade_id SERIAL NOT NULL,
	FOREIGN KEY (unidade_id) REFERENCES unidade(id),
	status BOOLEAN NOT NULL
	);